spring.application.name=QUESTION-SERVICE
server.port=7000
#
#
#
spring.datasource.url=jdbc:mysql://localhost:3306/micro_yt
spring.datasource.password=root
spring.datasource.username=root
#spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.import-check.enabled=false
spring.jpa.sql.show-sql=true
spring.jpa.hibernate.ddl-auto=update
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}
#
#
# Tell service where admin server is
spring.boot.admin.client.url=http://localhost:6060


# Show health details
management.endpoint.health.show-details=always




# Zipkin server URL
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Send 100% traces (for learning)
management.tracing.sampling.probability=1.0

# Actuator exposure
management.endpoints.web.exposure.include=*